import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import ModalProvider from "@/components/provider/modal-provider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { QueryClientProvider } from '@tanstack/react-query';
 
 
const inter = Poppins({weight:['200','400','600','700','800'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Post App",
  description: "Generated by Post App",
};
 
  export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session =  await auth();
  return (
    <SessionProvider session={session}> 
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        <ModalProvider />
      
        {children}
   
        </body>
    </html>
    </SessionProvider>
  );
}
